[build]
  # Build command
  command = "npm run build"
  
  # Output directory
  publish = "dist"
  
  # Environment variables
  environment = { NODE_VERSION = "18.17.0" }
  
# Build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Redirects for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Arabic language redirect
[[redirects]]
  from = "/ar/*"
  to = "/index.html"
  status = 200
  
# English language redirect  
[[redirects]]
  from = "/en/*"
  to = "/index.html"
  status = 200
  
# French language redirect
[[redirects]]
  from = "/fr/*"
  to = "/index.html"
  status = 200

# API redirects (if you have a backend)
[[redirects]]
  from = "/api/*"
  to = "https://your-api-domain.com/api/:splat"
  status = 200
  force = false

# Legacy URL redirects
[[redirects]]
  from = "/old-contact"
  to = "/#contact"
  status = 301
  
[[redirects]]
  from = "/old-services"
  to = "/#services"
  status = 301

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Content Security Policy (Enhanced)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; media-src 'self' https:; connect-src 'self' https://www.google-analytics.com https://api.gemini.google.com https://wa.me; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
    
    # Performance Headers
    Cache-Control = "public, max-age=31536000, immutable"

# Cache optimization for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# API headers (if you have API endpoints)
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Content-Type = "application/json"

# Arabic content optimization
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Language = "ar-DZ, en-US, fr-FR"
    
# Service Worker caching
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Environment-specific settings
[context.production.environment]
  VITE_ENV = "production"
  VITE_SITE_URL = "https://saidjlawyer.netlify.app"
  
[context.deploy-preview.environment]
  VITE_ENV = "preview"
  
[context.branch-deploy.environment]
  VITE_ENV = "development"

# Functions (if you use Netlify Functions)
[functions]
  directory = "netlify/functions"
  
# Edge functions
[edge_functions]
  directory = "netlify/edge-functions"

# Forms handling (for contact forms)
[forms]
  # Form settings will be automatically detected

# Large Media (for large files)
[large_media]
  # Large media files will be handled automatically

# Plugin settings
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  # Lighthouse configuration
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    audit_url = "/"
    
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://saidjlawyer.netlify.app"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing",
      "yandex"
    ]

# Custom build settings
[template.environment]
  VITE_GEMINI_API_KEY = "Your Gemini API Key"
  VITE_CONTACT_EMAIL = "contact@saidjlawyer.com"
  VITE_PHONE_NUMBER = "+213XXXXXXXXX"
  VITE_WHATSAPP_NUMBER = "+213XXXXXXXXX"
  VITE_SITE_NAME = "مكتب الأستاذ سعيد محمد للمحاماة"
  VITE_SITE_DESCRIPTION = "مكتب محاماة متخصص في جميع فروع القانون مع خبرة واسعة في الاستشارات القانونية"